apiVersion: batch/v1
kind: Job
metadata:
  name: my-job
spec:
  template:
    spec:
      containers:
      - name: cpulimit
        image: perfectmak/kubernetescpulimittest:latest
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 0.1
          requests:
            cpu: 0.1
      restartPolicy: Never
  backoffLimit: 4